INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('JAKUB','XYZ','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Michal','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Franek','FRANEK','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Stefan','BATORY','SURGEON');


INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PACJENT','PACJENTOWY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('KUBA','ZWYCZJANY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('MARCIN','STARY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('MAREK','NADZWYCZAJNY');

INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (10, 1, 1, '2024-01-05', 'X_RAY');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (70, 2, 2, '2024-01-11', 'X_RAY');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (3, 3, 4, '2022-11-02', 'MAMMOGRAM');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (22, 4, 2, '2021-01-02', 'MAMMOGRAM');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (18, 1, 3, '2021-01-02', 'EYE_EXAM');
