INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('JAKUB','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Michal','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Franek','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Stefan','GOSTKOWSKI','SURGEON');


INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PACJENT','PACJENTOWY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PACJENT','ZWYCZJANY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PACJENT','STARY');
INSERT INTO PATIENT (FIRST_NAME,LAST_NAME) VALUES ('PACJENT','NADZWYCZAJNY');

INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (30, 1, 1, '2024-01-02', 'X_RAY');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (30, 1, 2, '2024-01-02', 'X_RAY');
INSERT INTO VISIT (DURATION_IN_MINUTES, DOCTOR_ID, PATIENT_ID, VISIT_DATE, VISIT_TYPE)
VALUES (30, 1, 2, '2024-01-02', 'MAMMOGRAM');
