INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('JAKUB','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Michal','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Franek','GOSTKOWSKI','SURGEON');
INSERT INTO DOCTOR (FIRST_NAME,LAST_NAME,SPECIALIZATION) VALUES ('Stefan','GOSTKOWSKI','SURGEON');
